name: Gh-Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - name: add web support
        run: flutter create .
        working-directory: .
      - uses: erickzanardo/flutter-gh-pages@v3
